server:
  port: 8000

spring:
  profiles:
    active: dev-secret
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${jlumart.datasource.driver-class-name}
      url: jdbc:oracle:thin:@${jlumart.datasource.host}:${jlumart.datasource.port}:${jlumart.datasource.database}
      username: ${jlumart.datasource.username}
      password: ${jlumart.datasource.password}
  redis:
    host: ${jlumart.redis.host}
    port: ${jlumart.redis.port}
    database: ${jlumart.redis.database}
    password: ${jlumart.redis.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jlumart.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      jlumart:
        mapper: debug
        service: info
        controller: info
      org:
        springframework:
          data:
            redis: DEBUG

jlumart:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${jlumart.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: ${jlumart.jwt.user-secret-key}
    # 设置jwt过期时间
    user-ttl: 720000000
    # 设置前端传递过来的令牌名称
    user-token-name: Authorization
    # 设置jwt签名加密时使用的秘钥
    courier-secret-key: ${jlumart.jwt.courier-secret-key}
    # 设置jwt过期时间
    courier-ttl: 720000000
    # 设置前端传递过来的令牌名称
    courier-token-name: Authorization

  alioss:
    endpoint: ${jlumart.alioss.endpoint}
    access-key-id: ${jlumart.alioss.access-key-id}
    access-key-secret: ${jlumart.alioss.access-key-secret}
    bucket-name: ${jlumart.alioss.bucket-name}

  map:
    address: ${jlumart.map.address}
    longgitude: ${jlumart.map.longitude}
    latitude: ${jlumart.map.latitude}
    ak: ${jlumart.map.ak}
    output: json
