jlumart:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    host: 192.168.80.10
    port: 1521
    database: orcl
    username: jlumartadmin
    password: password
  alioss:
    endpoint: your-endpoint
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    bucket-name: your-bucket-name
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0

  jwt:
    admin-secret-key: your-secret-key
    user-secret-key: your-secret-key
    courier-secret-key: your-secret-key
  map:
    address: your-address
    longitude: your-longitude
    latitude: your-latitude
    ak: your-ak